package preact.test

import org.scalajs.dom
import preact.ComponentTest1
import preact.bindings.*
import preact.test.modifier.{*, given}

import scala.deriving.Mirror
import scala.scalajs.js
import scala.scalajs.js.annotation.JSExportTopLevel

def buildinTagWithChildren[
    Modifier <: AttributeModifier[?, ?] | ChildModifier
](
    tag: String,
    modifiers: Seq[Modifier]
): VNode =
  var jsAttribs = js.Dynamic.literal()
  var childrenArray = js.Array[Child]()

  modifiers.foreach {
    case am: AttributeModifier[?, ?] =>
      am(jsAttribs)
    case cm: ChildModifier =>
      cm(childrenArray)
  }

  h(tag, jsAttribs, childrenArray)

object DomElement:
  type Id = AttributeModifier["id", String]
  type Cls = AttributeModifier["class", String]
  type Disabled = AttributeModifier["disabled", Boolean]
  type OnClick =
    AttributeModifier["onClick", js.Function1[dom.MouseEvent, Unit]]

  type Modifier = Id | Cls | Disabled | OnClick | ChildModifier

inline def div(ms: DomElement.Modifier*) = buildinTagWithChildren("div", ms)
inline def span(ms: DomElement.Modifier*) = buildinTagWithChildren("span", ms)
inline def h3(ms: DomElement.Modifier*) = buildinTagWithChildren("h3", ms)
inline def button(ms: DomElement.Modifier*) =
  buildinTagWithChildren("button", ms)

// === Component API Examples ===

// We now try different approaches to define reusable components.
// We will first do it manually, then try to leverage scala3 metaprogramming.

// ===== Approach 1: Case class based components =====

case class Card(
    title: String,
    footer: Option[String],
    children: Children
):
  def render(self: Card): VNode =
    div(
      h3(title), // Card title
      div(
        children
      ), // Card content - spread children as modifiers
      footer match
        case Some(text) => div(text)
        case None       => NullChild
    )

// We want the Modifier Type and apply method to be autogenerated by
// scala3 metaprogramming in the future. The Modifiers should be derived from
// the component's case class fields, and the builder of an instance from AttributeModifiers
// should also be autogenerated.
object Card:
  type Modifier =
    AttributeModifier["title", String] | AttributeModifier["footer", String] |
      ChildModifier

  def apply(ms: Modifier*): VNode =
    var titleValue: String = ""
    var footerValue: Option[String] = None
    val childMods = js.Array[Child]()

    ms.foreach {
      case attr: AttributeModifier[?, String] =>
        attr.key match
          case "title"  => titleValue = attr.value
          case "footer" => footerValue = Some(attr.value)
      case cm: ChildModifier =>
        childMods += cm.child
    }

    val card = Card(titleValue, footerValue, childMods)
    card.render(card)

// ===== Approach 2: Case class component using Component.Derived but without enough generated code to be usefull =====
// Here type Modifier and apply method are mainly inside the class, not in the companion object.
// This shows how Component.Derived could be implemented.

case class Card2(
    title: String = "",
    footer: Option[String] = None,
    children: Children = js.Array()
) extends ComponentTest1.Derived[Card2]:
  def render: VNode =
    div(
      h3(title), // Card title
      div(
        children
      ), // Card content - spread children as modifiers
      footer match
        case Some(text) => div(text)
        case None       => NullChild
    )

  // ORIGINAL MANUAL IMPLEMENTATION (for reference):
  // type Modifier =
  //   AttributeModifier["title", String] | AttributeModifier["footer", String] |
  //     ChildModifier
  //
  // def apply(mod: Modifier): Card2 =
  //   mod match
  //     case am: AttributeModifier[?, ?] =>
  //       am.key match
  //         case "title" =>
  //           this.copy(title = am.value.asInstanceOf[String])
  //         case "footer" =>
  //           this.copy(footer = Some(am.value.asInstanceOf[String]))
  //         case _ => this
  //     case cm: ChildModifier =>
  //       this.copy(children = this.children.concat(js.Array(cm.child)))

object Card2:
  given comp: ComponentTest1[Card2] = ComponentTest1.derived

  type ModifierLike =
    AttributeModifier["title", String] | AttributeModifier["footer", String] |
      ChildModifier

  def apply(ms: ModifierLike*): VNode =
    comp.applyAll(Card2(), ms).render

// ==== Component Factory ====

class ComponentTest2[P, M](renderFn: NamedTuple.From[P] => VNode):
  type Props = NamedTuple.From[P]

  def apply(ms: M*): VNode =
    val props = ???
    renderFn(props)

def component[P, M](renderFn: NamedTuple.From[P] => VNode) =
  new ComponentTest2[P, M](renderFn)

type CardProps = (
    title: String,
    footer: Option[String],
    children: Children
)

// ideally this would be generated by a macro from the props tuple above
type CardPropsModifier =
  AttributeModifier["title", String] | AttributeModifier["footer", String] |
    ChildModifier

val Card3 = component[CardProps, CardPropsModifier]: props =>
  div(
    h3(props.title), // Card title
    div(
      props.children
    ), // Card content - spread children as modifiers
    props.footer match
      case Some(text) => div(text)
      case None       => NullChild
  )

// === Application Rendering, where all the versions are tested ===

def appContent =
  div(
    "id" := "greeting", // id attribute
    "class" := "container", // class attribute

    "This is a div element.", // child element

    span(
      "class" := "nested",
      "Nested span child element."
    ), // nested div as child

    // Button with disabled prop
    button(
      "disabled" := true,
      "Disabled Button"
    ),

    // Button with click handler
    button(
      "onClick" := (e => println("Button clicked!")),
      "Click me"
    ),

    // Card component with title and children
    Card(
      "title" := "My Card Title",
      "This is the content of the card.",
      div("A nested div inside the card.", button("Nested Button"))
    ),

    // Card component with title and children
    Card(
      "title" := "My Second Card with Footer",
      "footer" := "This is the footer text.",
      "This is the content of the second card."
    ),

    // Card2 component - using derived Component!
    Card2(
      "title" := "My Card2 with Footer",
      "footer" := "This is the footer text.",
      "This is Card2 content - auto-derived!"
    )
  )

@JSExportTopLevel("renderApp")
def renderApp(): Unit =
  val rootElement = dom.document.body
  render(appContent, rootElement)
