package preact.test

import org.scalajs.dom
import preact.bindings.*

import scala.scalajs.js
import scala.scalajs.js.annotation.JSExportTopLevel

class AttributeModifier[Key <: String, Value](val key: Key, val value: Value):
  inline def apply(jsAttribs: js.Dynamic): Unit =
    jsAttribs.updateDynamic(key)(value.asInstanceOf[js.Any])

extension [Key <: String, Value](key: Key)
  inline def :=(value: Value) = AttributeModifier(key, value)

class ChildModifier(val child: Child):
  inline def apply(childrenArray: js.Array[Child]): Unit =
    childrenArray.push(child.asInstanceOf[js.Any])

// Given conversions for children
given Conversion[String, ChildModifier]:
  inline def apply(str: String) = ChildModifier(str)
given Conversion[Int, ChildModifier]:
  inline def apply(num: Int) = ChildModifier(num)
given Conversion[Double, ChildModifier]:
  inline def apply(num: Double) = ChildModifier(num)
given Conversion[VNode, ChildModifier]:
  inline def apply(vnode: VNode) = ChildModifier(vnode)

def buildinTagWithChildren[
    Modifier <: AttributeModifier[?, ?] | ChildModifier
](
    tag: String,
    modifiers: Seq[Modifier]
): VNode =
  var jsAttribs = js.Dynamic.literal()
  var childrenArray = js.Array[Child]()

  modifiers.foreach {
    case am: AttributeModifier[?, ?] =>
      am(jsAttribs)
    case cm: ChildModifier =>
      cm(childrenArray)
  }

  h(tag, jsAttribs, childrenArray)

object DomElement:
  type Id = AttributeModifier["id", String]
  type Cls = AttributeModifier["class", String]
  type Disabled = AttributeModifier["disabled", Boolean]
  type OnClick =
    AttributeModifier["onClick", js.Function1[dom.MouseEvent, Unit]]

  type Modifier = Id | Cls | Disabled | OnClick | ChildModifier

inline def div(ms: DomElement.Modifier*) = buildinTagWithChildren("div", ms)
inline def span(ms: DomElement.Modifier*) = buildinTagWithChildren("span", ms)
inline def h3(ms: DomElement.Modifier*) = buildinTagWithChildren("h3", ms)
inline def button(ms: DomElement.Modifier*) =
  buildinTagWithChildren("button", ms)

// === component base types ===

type Children = js.Array[Child]

// ===== Example App =====

case class Card(
    title: String,
    footer: Option[String],
    children: Children
):
  def render(self: Card): VNode =
    div(
      h3(title), // Card title
      div(
        children
      ) // Card content - spread children as modifiers
    )

// We want the Modifier Type and apply method to be autogenerated by
// scala3 metaprogramming in the future. The Modifiers should be derived from
// the component's case class fields, and the builder of an instance from AttributeModifiers
// should also be autogenerated.
object Card:
  type Modifier =
    AttributeModifier["title", String] | AttributeModifier["footer", String] |
      ChildModifier

  def apply(ms: Modifier*): VNode =
    var titleValue: String = ""
    var footerValue: Option[String] = None
    val childMods = js.Array[Child]()

    ms.foreach {
      case title: AttributeModifier["title", String] =>
        titleValue = title.value
      case footer: AttributeModifier["footer", String] =>
        footerValue = Some(footer.value)
      case cm: ChildModifier =>
        childMods += cm.child
    }

    val card = Card(titleValue, footerValue, childMods)
    card.render(card)

def appContent =
  div(
    "id" := "greeting", // id attribute
    "class" := "container", // class attribute

    "This is a div element.", // child element

    span(
      "class" := "nested",
      "Nested span child element."
    ), // nested div as child

    // Button with disabled prop
    button(
      "disabled" := true,
      "Disabled Button"
    ),

    // Button with click handler
    button(
      "onClick" := (e => println("Button clicked!")),
      "Click me"
    ),

    // Card component with title and children
    Card(
      "title" := "My Card Title",
      "This is the content of the card.",
      div("A nested div inside the card.", button("Nested Button"))
    )
  )

@JSExportTopLevel("renderApp2")
def renderApp2(): Unit =
  val rootElement = dom.document.body
  render(appContent, rootElement)
