/**
 * Entry point for Scala Preact minimal example
 *
 * This loads the Scala.js compiled output and calls the exported renderApp function
 */

// Import the Scala.js compiled module
// The dist/main.js is generated by: bun run scala
import { renderApp } from "../dist/main.js";

// Call the exported renderApp function
// This is exported from MinimalExample.scala via @JSExportTopLevel("renderApp")
console.log("Loading Scala Preact example...");

if (typeof renderApp === "function") {
  console.log("Found renderApp function, calling it...");
  renderApp();
  console.log("App rendered successfully!");
} else {
  console.error("renderApp function not found!");
  console.error("Available exports:", Object.keys(window));
  console.error("Make sure to run: bun run scala");
}
