import "preact/debug";
import "../style.css";

/**
 * Entry point for Scala Preact minimal example
 *
 * This loads the Scala.js compiled output and calls the exported renderApp function
 */

// Import the Scala.js compiled module
// The dist/main.js is generated by: bun run scala
import { renderApp } from "../out/main.js";

// Call the exported renderApp function
// This is exported from MinimalExample.scala via @JSExportTopLevel("renderApp")
console.log("Loading Scala Preact example...");

renderApp();
